# Generated by Django 5.2.7 on 2025-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_vector',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
