# Generated by Django 5.2.7 on 2025-11-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_faq_question_vector'),
    ]

    operations = [
    ]
