# Generated by Django 5.2.7 on 2025-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20251104_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='A unique ID for this rule node', max_length=100, unique=True)),
                ('rule_data', models.JSONField(default=dict, help_text="The JSON object defining the rule's message and options")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='response_type',
            field=models.CharField(choices=[('text', 'Simple Text'), ('rich', 'Rich Options/Guided Flow')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='faq',
            name='rich_response',
            field=models.JSONField(blank=True, help_text="Used if response type is 'Rich Options.'", null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, help_text='Used if respone is Simple Text', null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_vector',
            field=models.JSONField(blank=True, editable=False, help_text='Auto-generated vector for search', null=True),
        ),
    ]
