# Generated by Django 5.2.7 on 2025-11-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, help_text="The client's industry (e.g., 'Technology', 'Legal', 'Retail')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, help_text="The client's main website (e.g., https://metascifor.com)", null=True),
        ),
    ]
