# Generated by Django 5.2.7 on 2025-11-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_client_industry_client_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_faqs', models.IntegerField(default=10, help_text='Maximum number of NLP-based FAQs allowed.')),
                ('max_leads', models.IntegerField(default=100, help_text='Maximum number of form submissions allowed per month.')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Is the subscription currently active?')),
                ('expires_on', models.DateField(blank=True, help_text='When the subscription expires', null=True)),
                ('payment_gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.plan')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.OneToOneField(blank=True, help_text="The client's current subscription package.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.subscription'),
        ),
    ]
